# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/openjdk:11.0
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "test"
          command: "mvn test"
      - run:
          name: "Generate Jacoco reports"
          command: "mvn clean test jacoco:report"
          environment:
            CODECOV_TOKEN: $CODECOV_TOKEN
      - run:
          name: "Publish code coverage to Codecov"
          command: "bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN"
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:checkstyle

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build-test:
          filters:
            branches:
              only: master
